### ISSUE TITLE
Expose Read/Write interface instead of filenames

### ISSUE THREAD

**Issue by Michael-F-Bryan** [sondrele/rust-bmp#24]
A lot of the time you'll be working on images entirely in-memory and don't want to write to the file system. Is it possible to expose an interface which reads from an `io::Read`er and writes to an `io::Write`? You probably already work with something like this internally, so it shouldn't require much extra work.

i.e. Something like this:

```rust
use std::io::{Read, Write};

fn from_reader<R: Read>(source: R) -> Result<Image> { /* ... */ }
fn to_writer<W: Write>(writer: W, image: Image) -> Result<()> { /* ... */ }
```

**Comment by sondrele** [comment]
Hey, thanks for reporting this! 

I just added a `from_reader` function to the library and a `to_writer` method to the `Image` struct, they are similar to the `open` and `save` functions, but takes a reader and a writer as arguments instead of a path.
The latest version is `0.3.0` on crates.io contains these changes. 

It doesn't seem like the documentation has been updated yet, it might need to be reconfigured in order for it to happen automatically, I'll look into this later.

Will close this for now, let me know if there's any other things you think should be supported
